"""first

Revision ID: 63a267acfe24
Revises: 
Create Date: 2020-11-04 16:09:58.640519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63a267acfe24'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sounds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('start', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('room', sa.String(length=64), nullable=True),
    sa.Column('made_by', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sounds_frequency'), 'sounds', ['frequency'], unique=False)
    op.create_index(op.f('ix_sounds_length'), 'sounds', ['length'], unique=False)
    op.create_index(op.f('ix_sounds_made_by'), 'sounds', ['made_by'], unique=False)
    op.create_index(op.f('ix_sounds_room'), 'sounds', ['room'], unique=False)
    op.create_index(op.f('ix_sounds_start'), 'sounds', ['start'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sounds_start'), table_name='sounds')
    op.drop_index(op.f('ix_sounds_room'), table_name='sounds')
    op.drop_index(op.f('ix_sounds_made_by'), table_name='sounds')
    op.drop_index(op.f('ix_sounds_length'), table_name='sounds')
    op.drop_index(op.f('ix_sounds_frequency'), table_name='sounds')
    op.drop_table('sounds')
    # ### end Alembic commands ###
